cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<pk>[-\w]+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<pk>[-\w]+)/$', views.cart_remove, name='cart_remove'),
]

eCom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls import url, handler400, handler403, handler404, handler500
from . import views
from eCom import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),  # admin site
    path('accounts/', include('django.contrib.auth.urls')),
    path('orders/', include(('orders.urls', 'order_create'), namespace='order_create')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('account/', include('account.urls')),
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
    path('Orders/', include('orders.urls')),
    path('fix/', views.FixPage)
]

handler404 = views.page_not_found


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    quantity.widget.attrs.update({'type': 'text', 'value': '1'})
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, id=pk)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Product, id=pk)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    #print(cart.cart)
    return render(request, 'cart/detail.html', {
        'cart': cart,
        'page_title': 'Корзина',
                  },)

templates/cart/detail.html
{% extends "base_generic.html" %}
{% block content %}
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Товары</th>
                                    <th>Цена за единицу</th>
                                    <th>Количество</th>
                                    <th>Цена</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                    {% with product=item.product %}
                                        <tr>
                                            <td class="shoping__cart__item">
                                                <img src="./../{{ product.prodimage.first.file }}" alt="" width="100" height="100">
                                                <h5>{{ product.title }}</h5>
                                            </td>
                                            <td class="shoping__cart__price">
                                                {{ item.price }} ₽
                                            </td>
                                            <td class="shoping__cart__quantity">{{ item.quantity }}</td>
                                            <td class="shoping__cart__total">
                                                {{ item.total_price }} ₽
                                            </td>
                                            <td class="shoping__cart__item__close">
                                                <a href="{% url "cart:cart_remove" product.id%}"><span class="icon_close"></span></a>
                                            </td>
                                        </tr>
                                    {% endwith %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="../shop/" class="primary-btn cart-btn">ПРОДОЛЖАТЬ ПОКУПКИ</a>
                        <a href="../cart/" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                            ОБНОВИТЬ КОРЗИНУ</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__continue">
                        <div class="shoping__discount">
                            <h5>Промокод</h5>
                            <form action="#">
                                <input type="text" placeholder="Введите промокод">
                                <button type="submit" class="site-btn">Введите промокод</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__checkout">
                        <h5>Итог</h5>
                        <ul>
                            <li>Промежуточная сумма <span>{{ cart.get_total_price }} ₽</span></li>
                            <li>Сумма <span>{{ cart.get_total_price }} ₽</span></li>
                        </ul>
                        <a href="../orders/create/" class="primary-btn">ПРИСТУПИТЬ К ОФОРМЛЕНИЮ ЗАКАЗА</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}