cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<pk>[-\w]+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<pk>[-\w]+)/$', views.cart_remove, name='cart_remove'),
]

eCom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls import url, handler400, handler403, handler404, handler500
from . import views
from eCom import settings

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),  # admin site
    path('accounts/', include('django.contrib.auth.urls')),
    path('orders/', include(('orders.urls', 'order_create'), namespace='order_create')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('account/', include('account.urls')),
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
    path('Orders/', include('orders.urls')),
    path('fix/', views.FixPage)
]

handler404 = views.page_not_found


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include

from . import views

urlpatterns = [
    url(r'^$', views.MainPage, name='mainpage'),
    url(r'^grid/$', views.ProductListView.as_view(), name='grid'),
    url(r'^index/$', views.index, name='grid'),
    url(r'^product/(?P<pk>[-\w]+)/$', views.ProductDetailView.as_view(), name='product-detail'),
    url(r'^product/edit/(?P<pk>[-\w]+)/$', views.ProductEditView, name='product-edit'),
    url(r'^product/image/remove/(?P<pk>[-\w]+)/(?P<prod_id>[-\w]+)/$', views.image_remove, name='image_remove'),
    url(r'^404/$', views.page404),
]

# url(r'^$', views.index, name='index'),
# url(r'^/$', views.ProductListView.as_view(), name='index'),
# url(r'^login/$', views.user_login, name='user_login')

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#https://green-point.ru/products/category/eco-bio-products

shop/models.py
import uuid
from django.conf import settings
from django.db import models
from django.utils import timezone


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class Manufacturer(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=255)
    site = models.URLField(max_length=200)

    def __str__(self):
        return self.title+" ("+self.site+")"


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=10000)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, null=False)
    price = models.FloatField(null=True)
    created_date = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    AVAILABILITY_STATUS = (
        ('i', 'In Stock'),
        ('s', 'Available at short notice'),
        ('o', 'Ordered on demand'),
        ('n', 'Not available'),
    )
    availability = models.CharField(max_length=1, choices=AVAILABILITY_STATUS, blank=True, default='n')
    weight = models.FloatField(null=True)
    sale = models.FloatField(null=True, default=0.0)
    discounted_price = models.FloatField(null=True, default=0.0)
    #title_image = models.ForeignKey('TitleImage', on_delete=models.SET_NULL, related_name='titlei', null=True)

    def __str__(self):
        return self.title+" |   "+self.category.__str__()+" |   "+self.manufacturer.__str__()

    class Meta:
        ordering = ['title']

    def availability_verbose(self):
        return dict(Product.AVAILABILITY_STATUS)[self.availability]

class Image(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    file = models.ImageField(upload_to='img', null=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=False, related_name="prodimage")
    #title_status = models.BooleanField(default=False)

# class TitleImage(models.Model):
#     product = models.ForeignKey(Product, on_delete=models.CASCADE, null=False, related_name="titleprod")
#     image = models.ForeignKey(Image, on_delete=models.CASCADE, null=False, related_name="titleimage")
#
# class Profile(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     phone_num = models.CharField(max_length=11, null=False)
#
#     def __str__(self):
#         return self.user.__str__()

# class Order(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4)
#     client = models.ForeignKey("Profile", on_delete=models.CASCADE, null=False)
#     sum_price = models.FloatField(null=False)
#     ORDER_STATUS = (
#         ('w', 'Waiting for payment'),
#         ('i', 'In processing'),
#         ('p', 'Package'),
#         ('t', 'Transmitted to delivery service'),
#         ('r', 'Return'),
#         ('c', 'Canceled by'),
#     )
#     status = models.CharField(max_length=1, choices=ORDER_STATUS, blank=True, default='w')
#     created_date = models.DateTimeField(default=timezone.now)
#
#     def __str__(self):
#         return self.id+"    |   "+self.status+"    |   "+self.created_date
#
#     def status_verbose(self):
#         return dict(Order.ORDER_STATUS)[self.status]
#
# class Delivery(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4)
#     price = models.FloatField(null=False, default=0.0)
#     address = models.CharField(max_length=255, null=False)
#     comments = models.CharField(max_length=255)
#     order = models.ForeignKey(Order, on_delete=models.CASCADE, null=False)
#
#     def __str__(self):
#         return self.id
#
# class OrderInstance(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE, null=False)
#     order = models.ForeignKey(Order, on_delete=models.CASCADE, null=False)

shop/forms.py
from django import forms
from .models import Product
from shop.models import Category


class LoginForm(forms.Form):
    username = forms.CharField()
    username.widget.attrs.update({'class': 'input100', 'type': 'text', 'name': 'email', 'placeholder': 'Email'})
    password = forms.CharField(widget=forms.PasswordInput)
    password.widget.attrs.update({'class': 'input100', 'name': 'pass', 'placeholder': 'Password'})

class EditForm(forms.Form):
    price = forms.FloatField(min_value=0.01)
    description = forms.CharField(widget=forms.Textarea, max_length=5000)
    discounted_price = forms.FloatField(min_value=0.01)
    #sale = forms.FloatField(max_value=100)
    title = forms.CharField(max_length=255)
    category = forms.MultipleChoiceField(choices=[(item.id, item.title) for item in Category.objects.all()])
    weight = forms.FloatField(min_value=0.0)
    file = forms.ImageField(label=u'Фотографии', widget=forms.FileInput(attrs={'multiple': 'multiple'}))

class SearchForm(forms.Form):
    input = forms.CharField(max_length=100)
    input.widget.attrs.update({'type': '"text"', 'placeholder': '"Что вам нужно?"'})

class SideBarForm(forms.Form):
    minamount = forms.CharField()
    maxamount = forms.CharField()
    minamount.widget.attrs.update({'id': 'minamount', 'type': 'text'})
    maxamount.widget.attrs.update({'id': 'maxamount', 'type': 'text'})
# title = models.CharField(max_length=255)
#     description = models.TextField(max_length=10000)
#     manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, null=False)
#     price = models.FloatField(null=True)
#     created_date = models.DateTimeField(default=timezone.now)
#     category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
#     AVAILABILITY_STATUS = (
#         ('i', 'In Stock'),
#         ('s', 'Available at short notice'),
#         ('o', 'Ordered on demand'),
#         ('n', 'Not available'),
#     )
#     availability = models.CharField(max_length=1, choices=AVAILABILITY_STATUS, blank=True, default='n')
#     weight = models.FloatField(null=True)
#     sale = models.FloatField(null=True, default=0.0)
#     discounted_price = models.FloatField(null=True, default=0.0)

shop/views.py
from django.core.files.base import ContentFile
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
# Create your views here.
from django.views import generic, View
from django.views.decorators.http import require_POST
from cart.forms import CartAddProductForm
from .models import Product, Category, Image
from .forms import LoginForm, EditForm, SearchForm, SideBarForm
from django.contrib.auth import authenticate, login


def MainPage(request):
    paginate = 6

    try:
        if request.session['cat_id'] != request.GET.get('cat_id'):
            request.session['cat_id'] = request.GET.get('cat_id')
    except:
        request.session['cat_id'] = request.GET.get('cat_id')

    try:
        if request.session['search'] != request.GET.get('search'):
            request.session['search'] = request.GET.get('search')
    except:
        request.session['search'] = request.GET.get('search')

    form = SideBarForm(
        initial={'minamount': Product.objects.values('discounted_price').order_by('discounted_price').first(),
                 'maxamount': Product.objects.values('discounted_price').order_by('discounted_price').last(),
                 })
    search_form = SearchForm()
    min_price = Product.objects.values('discounted_price').order_by('discounted_price').first()['discounted_price']
    max_price = Product.objects.values('price').order_by('price').last()['price']

    if request.GET.get('minamount') is not None or request.GET.get('maxamount') is not None:
        min_price = float(request.GET.get('minamount')[:-2])
        max_price = float(request.GET.get('maxamount')[:-2])

    if request.session['cat_id'] is None:
        prod_list = Product.objects.filter(price__lte=max_price + 1).exclude(discounted_price__lte=min_price - 1)
    else:
        prod_list = Product.objects.filter(category=request.session['cat_id'], price__lte=max_price + 1).exclude(
            discounted_price__lte=min_price - 1)

    if request.session['search'] is not None:
        prod_list = Product.objects.filter(title__contains=request.session['search'])

    if request.POST.get('input'):
        prod_list = Product.objects.filter(title__contains=request.POST.get('input').upper())

    paginator = Paginator(prod_list, paginate)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    return render(request, 'shop/product_list.html', {
        'side_form': form,
        'search_form': search_form,
        'page_title': 'Органический магазин',
        'sale_list': Product.objects.all().exclude(sale=0),
        'category_list': Category.objects.all(),
        'price_range': [Product.objects.values('discounted_price').order_by('discounted_price').first(),
                        Product.objects.values('price').order_by('price').last()],
        'page_obj': page_obj,
    }
                  )


class ProductListView(generic.ListView):
    model = Product
    template_name = "shop/product_list.html"
    paginate_by = 6
    category = None
    search = ''
    form = None

    def get_queryset(self):
        print("in 0")
        # print()
        try:
            category = Category.objects.get(id=self.kwargs['cat_id'])
            print("in 1")
            print(category)
            return Product.objects.all().filter(category=category)
        except KeyError:
            print("in 2")
            return Product.objects.all()


    def post(self, request):
        self.search = self.form.input
        print(self.search)
        return HttpResponse(200)

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['sale_list'] = Product.objects.all().exclude(sale=0)
        context['category_list'] = Category.objects.all()
        context['page_title'] = "Органический магазин"
        context['price_range'] = [Product.objects.values('price').order_by('price').first(),
                                  Product.objects.values('price').order_by('price').last()]
        # print(context)
        return context


class EIndexView(View):

    def get(self, request):
        context = {}
        all_product = Product.objects.all().order_by('created_date')
        current_page = Paginator(all_product, 6)
        page = request.GET.get('page')
        try:
            context['product_lst'] = current_page.page(page)
        except PageNotAnInteger:
            context['product_lst'] = current_page.page(1)
        except EmptyPage:
            context['product_lst'] = current_page.page(current_page.num_pages)
        return render('shop/grid_content.html', context)


def index(request):
    sale_list = Product.objects.all().exclude(sale=0)
    prod_list = Product.objects.all()
    return render(
        request,
        '404.html',
        context={'sale_list': sale_list,
                 'prod_list': prod_list,
                 }
    )


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'product_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['sale_list'] = Product.objects.all().exclude(sale=0)
        context['category_list'] = Category.objects.all()
        context['page_title'] = "О Продукте"
        context['price_range'] = [Product.objects.values('price').order_by('price').first(),
                                  Product.objects.values('price').order_by('price').last()]
        context['cart_product_form'] = CartAddProductForm()
        return context

    def product_detail_view(request, pk):
        try:
            product_id = Product.objects.get(pk=pk)
            print(Product.objects.get(pk=pk))
        except Product.DoesNotExist:
            raise Http404("Product does not exist")
        return render(request, 'product_detail.html', context={'product': product_id})


def ProductEditView(request, pk):
    product = Product.objects.get(pk=pk)
    if not request.user.is_anonymous and (request.user.is_staff or request.user.userprofile.editor):
        if request.method == 'POST':
            form = EditForm(request.POST, request.FILES)
            if form.is_valid():
                print(request.FILES['file'])
                for f in request.FILES.getlist('file'):
                    # data = f.read()
                    # print(data)
                    print(product)
                    image = Image(product=product, file=f)
                    image.save()
                return HttpResponseRedirect('/shop/product/edit/' + pk + '/')
            return HttpResponse(504)
        else:
            print(1)
            data = {'price': product.price,
                    'description': product.description,
                    'discounted_price': product.discounted_price,
                    'sale': product.sale,
                    'title': product.title,
                    'weight': product.weight
                    }
            form = EditForm(initial=data)
            return render(request, 'shop/product_edit.html', context={'form': form,
                                                                      'page_title': 'Редактор',
                                                                      'product': product})
    else:
        return redirect('/shop/404/')


def page404(request):
    return render(request, '404.html')


def ProductRemove(request, pk):
    print('in ProductRemove')


def ProductSave(request, pk):
    print('in ProductSave')


def image_remove(request, pk, prod_id):
    image = Image.objects.get(pk=pk)
    image.delete()
    return redirect('shop:product-edit', prod_id)

# return render(
#         request,
#         'index.html',
#         context={'num_books': num_books, 'num_instances': num_instances,
#                  'num_instances_available': num_instances_available, 'num_authors': num_authors,
#                  'num_visits': num_visits},  # num_visits appended
#         )

templates/shop/grid_content.html
{% extends "base_generic.html" %}
{% block content %}
    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-5">
                    {% block grid_sidebar %}{% endblock %}
                </div>
                <div class="col-lg-9 col-md-7">
                    {% block grid_content %}{% endblock %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/shop/product_edit.html
{% extends "base_generic.html" %}
{% block content %}
    <!-- Product Details Section Begin -->
    <section class="product-details spad">
        <div class="container">
            <div class="row">
                <form method="post" enctype="multipart/form-data">
                <div class="col-lg-12">
                    <div class="product__details__text">
                        <h3>{{ form.title }}</h3>
                        <div class="product__details__rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                            <span>(18 reviews)</span>
                        </div>
                        {% if product.sale %}
                            <h3>Цена со скидкой</h3><div class="product__details__price">{{ form.discounted_price }}
                            <h3>Цена без скидки</h3>{{ form.price }}</div>
                        {% endif %}
                    <div>{{ form.description }}</div>
                        <div>{{ form.category }}</div>
                        <div>
                            <br><br><br>
                        <h3>Weight</h3>
                        <div>{{ form.weight }}</div>
                        </div>
                        <div><tr class="product__details__pic">
                    {% if product.prodimage %}
                        {% for image in product.prodimage.all %}
                            <tr>
                            <td class="shoping__cart__item"><img data-imgbigurl="../../../{{ image.file }}"
                                src="../../../{{ image.file }}" alt="" width="200" height="200">
                            </td>
                            <td class="shoping__cart__item__close">
                                                <a href="{% url "shop:image_remove" image.id product.id%}"><span class="icon_close"></span></a>
                            </td>
                            </tr>
                        {% endfor %}
                        {{ form.file }}
                    {% endif %}
                        </div>
                    </div>
                </div>
                {% csrf_token %}
                    <button type="submit" class="site-btn">SAVE</button>
                </form>
            </div>
            </div>
        </div>
    </section>
    <!-- Product Details Section End -->


    <!-- Footer Section Begin -->
{% endblock %}

templates/shop/product_list.html
{% extends "shop/sidebar_generic.html" %}
{% load tag_library %}
{% block grid_content %}
    <div class="product__discount">
                        <div class="section-title product__discount__title">
                            <h2>Распродажа</h2>
                        </div>
                        <div class="row">
                            <div class="product__discount__slider owl-carousel">
                                {% for sale_item in sale_list %}
                                    <div class="col-lg-4">
                                    <div class="product__discount__item">
                                        <div class="product__discount__item__pic set-bg"
                                            data-setbg="/{{ sale_item.prodimage.first.file }}">
                                            <div class="product__discount__percent">{{ sale_item.sale|toFixed }} %</div>
                                            <ul class="product__item__pic__hover">
                                                <li><a href="/shop/product/{{ sale_item.id}}/"><i class="fa fa-shopping-cart"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="product__discount__item__text">
                                            <h5><a href="/shop/product/{{ sale_item.id}}/">{{ sale_item.title }}</a></h5>
                                            <div class="product__item__price">{{ sale_item.discounted_price }}<span>{{ sale_item.price }}</span></div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
    <div class="filter__item">
                        <div class="row">
                            <div class="col-lg-4 col-md-5">
                                <div class="filter__sort">
                                    <span>Сортировать по</span>
                                    <select>
                                        <option value="0">По умолчанию</option>
                                        <option value="0">По умолчанию</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4">
                                <div class="filter__found">
                                    <h6><span>{{ product_list.count }}</span> Найдено товаров</h6>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-3">
                                <div class="filter__option">
                                    <span class="icon_grid-2x2"></span>
                                    <span class="icon_ul"></span>
                                </div>
                            </div>
                        </div>
                    </div>
    <div class="row">
                        {% if page_obj %}
                            {% for product in page_obj %}
                                <div class="col-lg-4 col-md-6 col-sm-6">
                                    <div class="product__item">
                                        <div class="product__item__pic set-bg" data-setbg="/{{ product.prodimage.first.file }}" >
                                            <ul class="product__item__pic__hover">
                                                <li><a href="/shop/product/{{ product.id}}/"><i class="fa fa-shopping-cart"></i></a></li>
                                            </ul>
                                        </div>
                                        <div class="product__item__text">
                                            <h6><a href="#">{{ product.title }}</a></h6>
                                            {% if product.sale %}
                                                <h5>{{ product.discounted_price }} ₽ </h5><s>{{ product.price }} ₽</s>
                                            {% else %}
                                                <h5>{{ product.price }} ₽</h5>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="/img/404_Item.jpg">
                                    <ul class="product__item__pic__hover">
                                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                                        <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6><a href="#">!!!!!!!!!!!</a></h6>
                                    <h5>$404</h5>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <div class="product__pagination">
                    {% if page_obj.has_previous %}
                        <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">previous</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <a href="?{% url_replace request 'page' page_obj.next_page_number %}">next</a>
                        <a href="?{% url_replace request 'page' page_obj.paginator.num_pages %}">last</a>
                    {% endif %}
                    </div>
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

{% endblock %}

templates/shop/sidebar_generic.html
{% extends "shop/grid_content.html" %}
{% load tag_library %}
{% block grid_sidebar %}
    <div class="sidebar">
        <div class="sidebar__item">
            <h4>Категории</h4>
            {% if category_list %}
                <ul>
                    {% for category in category_list %}
                        <li><a href="?{% url_replace request 'cat_id' category.id %}">{{ category.title }}</a></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <form method="get">
            <div class="sidebar__item">
                <h4>Цена</h4>
                <div class="price-range-wrap">
                    <div class="price-range ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content"
                         data-min={{ price_range.0.discounted_price|toInt }} data-max={{ price_range.1.price|toInt }}>
                        <div class="ui-slider-range ui-corner-all ui-widget-header"></div>
                        <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                        <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                    </div>
                    <div class="range-slider">
                        <div class="price-input">
                            {{ side_form.minamount }}
                            {{ side_form.maxamount }}
                        </div>
                        <button type="submit" class="site-btn">ПОИСК</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}